name: iOS Deploy

on:
#  workflow_dispatch
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: setup fastlane
      run: bundle install

    - name: build to appcenter
      run: bundle exec fastlane app_center
#      env:
#        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
#        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
